spring:
  application:
    name: inventory-management

#Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#Email SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#Redis Configuration
  cache:
    type: redis
    redis:
      time-to-live: 10m

  data:
    redis:
      client-type: jedis
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: 5s
      ssl:
        enabled: ${REDIS_SSL:false}

server:
  servlet:
    context-path: /api/v1
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB

app:
  cors:
    allowed-origin: http://localhost:5173

#Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

#JWT Configuration
jwt:
  secret: ${JWT_SECRET}